---
- name: Deploy lamp stack application
  hosts: all
  become: true
  tasks:
  - include_tasks: tasks/common.yml

- name: Configure MariaDB on lamp-db
  hosts: lamp-db
  become: true
  tasks:
  - include_tasks: tasks/db.yml

- name: Install and configure dependencies on lamp-web
  hosts: lamp-web
  become: yes
  tasks:
  - include_tasks: tasks/web.yml